# Generated by Django 4.2.4 on 2023-08-22 08:03

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Computation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created")),
                ("bsdd_data", models.JSONField(default=dict)),
                ("bsda_data", models.JSONField(default=dict)),
                ("bsff_data", models.JSONField(default=dict)),
                ("bsdasri_data", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Computation",
                "verbose_name_plural": "Computations",
                "ordering": ("-created",),
            },
        ),
    ]
