# Generated by Django 4.2.5 on 2023-09-11 14:12

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Computation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField(default=2023)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created")),
                ("total_bs_created", models.PositiveBigIntegerField(default=0)),
                ("total_quantity_processed", models.PositiveBigIntegerField(default=0)),
                ("total_companies_created", models.PositiveBigIntegerField(default=0)),
                ("quantity_processed_total", models.JSONField(default=dict)),
                ("quantity_processed_yearly", models.JSONField(default=dict)),
                ("bs_created_yearly", models.JSONField(default=dict)),
                ("quantity_processed_weekly", models.JSONField(default=dict)),
                ("quantity_processed_sunburst", models.JSONField(default=dict)),
                ("bsdd_counts_weekly", models.JSONField(default=dict)),
                ("bsda_counts_weekly", models.JSONField(default=dict)),
                ("bsff_counts_weekly", models.JSONField(default=dict)),
                ("bsdasri_counts_weekly", models.JSONField(default=dict)),
                ("bsdd_quantities_weekly", models.JSONField(default=dict)),
                ("bsda_quantities_weekly", models.JSONField(default=dict)),
                ("bsff_quantities_weekly", models.JSONField(default=dict)),
                ("bsdasri_quantities_weekly", models.JSONField(default=dict)),
                ("produced_quantity_by_category", models.JSONField(default=dict)),
                ("company_created_total_life", models.JSONField(default=dict)),
                ("user_created_total_life", models.JSONField(default=dict)),
                ("company_created_weekly", models.JSONField(default=dict)),
                ("user_created_weekly", models.JSONField(default=dict)),
                ("company_counts_by_category", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Computation",
                "verbose_name_plural": "Computations",
                "ordering": ("-created",),
            },
        ),
    ]
