# Generated by Django 4.2.4 on 2023-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_computation_bs_created_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="total_bs_created",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="total_companies_created",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="total_quantity_processed",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
