# Generated by Django 4.2.4 on 2023-08-23 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0003_computation_total_bs_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computation",
            old_name="quantity_processed_sunburst_figure",
            new_name="quantity_processed_sunburst",
        ),
    ]
