# Generated by Django 4.2.5 on 2023-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0003_computation_bsvhu_quantities_weekly"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="bsff_packagings_counts_weekly",
            field=models.JSONField(default=dict),
        ),
    ]
