# Generated by Django 4.2.5 on 2023-11-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0004_computation_bsff_packagings_counts_weekly"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="icpe_list",
            field=models.JSONField(default=dict),
        ),
    ]
