# Generated by Django 5.0.1 on 2024-01-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_computation_bsff_packagings_counts_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='computation',
            name='icpe_data',
            field=models.JSONField(default=dict),
        ),
    ]
