# Generated by Django 4.2.4 on 2023-09-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0004_rename_quantity_processed_sunburst_figure_computation_quantity_processed_sunburst"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="bsff_quantities_weekly",
            field=models.JSONField(default=dict),
        ),
    ]
