# Generated by Django 5.0.1 on 2024-02-05 10:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_computation_icpe_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartementsComputation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=2023)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                ("rubrique", models.TextField()),
                ("code_departement", models.TextField()),
                ("nom_departement", models.TextField()),
                ("code_region", models.TextField()),
                ("stats", models.JSONField(default=dict)),
                ("graph", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Regions Computation",
                "verbose_name_plural": "Regions Computations",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="InstallationsComputation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=2023)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                ("code_aiot", models.TextField()),
                ("rubrique", models.TextField()),
                ("raison_sociale", models.TextField()),
                ("siret", models.TextField()),
                ("adresse1", models.TextField()),
                ("adresse2", models.TextField()),
                ("code_postal", models.TextField()),
                ("commune", models.TextField()),
                ("etat_activite", models.TextField()),
                ("regime", models.TextField()),
                ("quantite_autorisee", models.FloatField()),
                ("unite", models.TextField()),
                ("geometry", models.JSONField(default=dict)),
                ("cumul_quantite_traitee", models.FloatField()),
                ("moyenne_quantite_journaliere_traitee", models.FloatField()),
                ("graph", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Installations Computation",
                "verbose_name_plural": "Installations Computations",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="RegionsComputation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=2023)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                ("rubrique", models.TextField()),
                ("code_region", models.TextField()),
                ("nom_region", models.TextField()),
                ("stats", models.JSONField(default=dict)),
                ("graph", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Regions Computation",
                "verbose_name_plural": "Regions Computations",
                "ordering": ("-created",),
            },
        ),
    ]
