# Generated by Django 4.2.4 on 2023-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0005_computation_bsff_quantities_weekly"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="all_bsds_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="computation",
            name="company_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="computation",
            name="user_data",
            field=models.JSONField(default=dict),
        ),
    ]
