# Generated by Django 4.2.4 on 2023-09-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0006_computation_all_bsds_data_computation_company_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="year",
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
