# Generated by Django 5.0.1 on 2024-02-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_departementscomputation_installationscomputation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="installationscomputation",
            name="geometry",
        ),
        migrations.AddField(
            model_name="installationscomputation",
            name="latitude",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="installationscomputation",
            name="longitude",
            field=models.FloatField(default=None, null=True),
        ),
    ]
