# Generated by Django 4.2.4 on 2023-09-07 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0007_computation_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computation",
            name="all_bsds_data",
        ),
        migrations.RemoveField(
            model_name="computation",
            name="bsda_data",
        ),
        migrations.RemoveField(
            model_name="computation",
            name="bsdasri_data",
        ),
        migrations.RemoveField(
            model_name="computation",
            name="bsdd_data",
        ),
        migrations.RemoveField(
            model_name="computation",
            name="bsff_data",
        ),
        migrations.RemoveField(
            model_name="computation",
            name="company_data",
        ),
        migrations.RemoveField(
            model_name="computation",
            name="user_data",
        ),
    ]
