# Generated by Django 5.0.1 on 2024-02-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_remove_installationscomputation_geometry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installationscomputation",
            name="adresse1",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="adresse2",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="code_postal",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="commune",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="cumul_quantite_traitee",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="etat_activite",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="moyenne_quantite_journaliere_traitee",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="quantite_autorisee",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="raison_sociale",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="regime",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="installationscomputation",
            name="unite",
            field=models.TextField(null=True),
        ),
    ]
