# Generated by Django 5.0.1 on 2024-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0008_alter_installationscomputation_adresse1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installationscomputation",
            name="graph",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
