# Generated by Django 4.2.4 on 2023-09-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0008_remove_computation_all_bsds_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="bs_created_yearly",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="computation",
            name="quantity_processed_yearly",
            field=models.JSONField(default=dict),
        ),
    ]
