# Generated by Django 5.0.1 on 2024-02-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0009_alter_installationscomputation_graph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installationscomputation",
            name="siret",
            field=models.TextField(null=True),
        ),
    ]
