# Generated by Django 4.2.4 on 2023-09-07 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0009_computation_bs_created_yearly_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computation",
            name="bs_created_total",
        ),
    ]
