# Generated by Django 5.0.1 on 2024-02-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stats",
            "0011_rename_code_departement_departementscomputation_code_departement_insee_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="departementscomputation",
            index=models.Index(
                fields=["year", "rubrique"], name="stats_depar_year_652343_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departementscomputation",
            index=models.Index(
                fields=["year", "rubrique", "code_departement_insee"],
                name="stats_depar_year_1dd873_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="installationscomputation",
            index=models.Index(
                fields=["year", "rubrique"], name="stats_insta_year_cd8810_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installationscomputation",
            index=models.Index(
                fields=["year", "rubrique", "code_aiot"],
                name="stats_insta_year_2f47f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regionscomputation",
            index=models.Index(
                fields=["year", "rubrique"], name="stats_regio_year_ec6475_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regionscomputation",
            index=models.Index(
                fields=["year", "rubrique", "code_region_insee"],
                name="stats_regio_year_196c35_idx",
            ),
        ),
    ]
