# Generated by Django 5.0.1 on 2024-02-19 14:08

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_departementscomputation_stats_depar_year_652343_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranceComputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=2023)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('rubrique', models.TextField()),
                ('quantite_autorisee', models.FloatField(null=True)),
                ('nombre_installations', models.FloatField(default=0)),
                ('cumul_quantite_traitee', models.FloatField(null=True)),
                ('moyenne_quantite_journaliere_traitee', models.FloatField(null=True)),
                ('taux_consommation', models.FloatField(null=True)),
                ('graph', models.JSONField(default=dict, null=True)),
            ],
            options={
                'verbose_name': 'France Computation',
                'verbose_name_plural': 'France Computations',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['year', 'rubrique'], name='stats_franc_year_04c799_idx')],
            },
        ),
    ]
