# Generated by Django 5.0.1 on 2024-03-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0013_francecomputation"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="bsda_bordereaux_created",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="bsda_quantity_processed",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="bsdasri_bordereaux_created",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="bsdasri_quantity_processed",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="bsdd_bordereaux_created",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="bsdd_quantity_processed",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="bsff_bordereaux_created",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="bsff_quantity_processed",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="bsvhu_bordereaux_created",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="bsvhu_quantity_processed",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
