# Generated by Django 5.0.1 on 2024-03-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0014_computation_bsda_bordereaux_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="mean_packagings_by_bsff",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="computation",
            name="mean_quantity_by_bsff_packagings",
            field=models.FloatField(default=0),
        ),
    ]
