# Generated by Django 5.0.1 on 2024-03-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0015_computation_mean_packagings_by_bsff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computation",
            name="mean_packagings_by_bsff",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="computation",
            name="mean_quantity_by_bsff_packagings",
            field=models.FloatField(default=0, null=True),
        ),
    ]
