# Generated by Django 5.0.4 on 2024-05-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_alter_computation_mean_packagings_by_bsff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computation',
            name='bsd_non_dangerous_bordereaux_created',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computation',
            name='bsd_non_dangerous_counts_weekly',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='computation',
            name='bsd_non_dangerous_quantities_weekly',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='computation',
            name='bsd_non_dangerous_quantity_processed',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
