# Generated by Django 5.0.4 on 2024-05-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_computation_bsdd_non_dangerous_bordereaux_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computation',
            name='quantity_processed_non_dangerous_yearly',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computation',
            name='total_quantity_processed_non_dangerous',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
