# Generated by Django 5.2 on 2025-06-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_computation_quantity_processed_non_dangerous_yearly_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartementsComputation',
        ),
        migrations.DeleteModel(
            name='FranceComputation',
        ),
        migrations.DeleteModel(
            name='InstallationsComputation',
        ),
        migrations.DeleteModel(
            name='RegionsComputation',
        ),
    ]
